# terminal-delight palette, generated by omarchy-theme-set-templates.
#
# Install as ~/.config/omarchy/themed/terminal-delight.toml.tpl and point
# terminal-delight at the rendered output:
#
#   export TD_THEME="$HOME/.local/state/omarchy/current/theme/terminal-delight.toml"
#
# terminal-delight polls that path's mtime every 300ms and reparses on change, so a
# theme switch retints the running terminal without a restart. No post_theme_commands
# entry is needed. See docs/terminal-delight-on-omarchy.md.
#
# KNOWN GAP: this file carries no [effects] block, so every theme switch resets
# scanlines / bloom / curvature to terminal-delight's defaults. The fix is a
# $TD_PALETTE overlay in terminal-delight that layers colour over an unchanged
# identity — do not paper over it by baking effects in here, that hands Omarchy a
# decision that isn't its to make.

name = "omarchy"
icon = "◆"

[colors]
bg      = "{{ background }}"
surface = "{{ lighter_background }}"
text    = "{{ foreground }}"
accent  = "{{ accent }}"
faint   = "{{ muted }}"
cursor  = "{{ bright_foreground }}"

# ANSI 16. Index 8 is `muted` because the theming doc says muted doubles as
# color8; index 7 and 15 are the two foreground stops of the neutral ramp.
ansi = [
  "{{ darker_background }}", "{{ red }}",        "{{ green }}",        "{{ yellow }}",
  "{{ blue }}",              "{{ magenta }}",    "{{ cyan }}",         "{{ foreground }}",
  "{{ muted }}",             "{{ bright_red }}", "{{ bright_green }}", "{{ bright_yellow }}",
  "{{ bright_blue }}",       "{{ bright_magenta }}", "{{ bright_cyan }}", "{{ bright_foreground }}",
]

[font]
family      = "JetBrains Mono"
size        = 14.0
cell_height = 20.0
